# Exclude hidden files, init, tensorrt folders, protobuf generated files, markdown files, and DB model.py files
exclude: ^(.*/\..*|.*__init__.py|.*tensorrt.*|.*_pb2.py|.*.md|.*.ts|.*.tsx|.*.css|.*tsconfig.json)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files # check that we're not committing big files to git, excluding lfs files.
        args: ["--maxkb=1000"] # set max file size to 1000KB
      - id: check-ast # check if valid python file
      - id: check-docstring-first # File comments should come before imports
      - id: check-json # make sure valid json
      - id: check-merge-conflict # check if left in merge conflict lines
      - id: check-yaml
      - id: debug-statements # check if left in debug statements
      - id: end-of-file-fixer
      - id: no-commit-to-branch # Prevents direct commits to master
      - id: requirements-txt-fixer # sort requirements
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--blocked-extension", "js"]
        name: isort (python)
        files: src/|tests/
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        files: src/|tests/
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0 # pick a git hash / tag to point to
    hooks:
      - id: flake8
        files: src/|tests/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.940 # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        files: src/|tests/
        additional_dependencies:
          [
            "types-requests",
            "mypy-protobuf",
            "types-mock",
            "sqlalchemy[mypy]<2.0.0",
          ]
  # - repo: https://github.com/pre-commit/mirrors-pylint
  - repo: https://github.com/pycqa/pylint
    rev: v2.14.1 # Use the sha / tag you want to point at
    hooks:
      - id: pylint
        language: system
        files: src/|tests/
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: src/|tests/
  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.16.0
    hooks:
      - id: sqlfmt
        language_version: python
        files: dbt/|src/load/
        types: [file, sql]
